workflows:
  unity-ios-workflow:
    name: Unity iOS Build
    instance_type: mac_mini_m2
    environment:
      xcode: latest
    scripts:
      - name: Build ipa
        working_directory: имя_папки_на_github
        script: |
          xcodebuild -project Unity-iPhone.xcodeproj \
            -scheme Unity-iPhone \
            -configuration Release \
            -sdk iphoneos \
            -archivePath build/Unity-iPhone.xcarchive \
            archive
          
          xcodebuild -exportArchive \
            -archivePath build/Unity-iPhone.xcarchive \
            -exportPath build/output \
            -exportOptionsPlist <(echo '<dict><key>method</key><string>development</string></dict>')
    artifacts:
      - '**/build/output/*.ipa'
